- name: Cleanup old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

#- name: Download backend Code and Extract it
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: "{{ app_loc }}"
#    remote_src: yes

- name: Download backend Code and Extract it
  ansible.builtin.unarchive:
#    src: http://{{ lookup('aws_ssm', 'artifactory_username', region='us-east-1' ) }}:{{ lookup('aws_ssm', 'artifactory_password', region='us-east-1' ) }}@artifactory.techadda.co:8081/artifactory/{{ component }}/{{ component }}-{{ lookup('aws_ssm', '{{env}}.{{component}}.app_version', region='us-east-1' ) }}.zip
    src: curl -u admin:Admin@123 -O "https://artifactory.techadda.co:8082/artifactory/frontend/frontend-1.0.0.zip"
    dest: "{{ app_loc }}"
    remote_src: yes