groups:
  - name: Infra alerts_Sever
    rules:
      - alert: ServerDownAlert
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert

  - name: Infra alerts
    rules:
      - alert: ServiceDownAlert_Service
        expr: up ! == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service Down Alert




