groups:
  - name: Infra alerts_Sever
    rules:
      - alert: ServerDownAlert
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert

      - alert: FrontendServiceDownAlert
        expr: node_systemd_unit_state{name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Frontend Service Down Alert

      - alert: BackendServiceDownAlert
        expr: node_systemd_unit_state{name="backend.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert

      - alert: mysqlServiceDownAlert
        expr: node_systemd_unit_state{name="mysqld.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: mysql service Down Alert






